version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    # template = '<#42E66C> </><b>{{.Parent}}{{ .Path }}</b>'
    template = '<b>{{.Parent}}{{ .Path }}</b>'
    foreground = '#F1FA8C'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    template = '<#ffffff> on </><b>{{ .HEAD }}</b>'
    foreground = '#43CCEA'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '{{ .FormattedMs }} '
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
      style = 'roundrock'

  [[blocks.segments]]
    template = 'py@{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}-{{ end }}{{ .Full }}{{ end }} '
    foreground = '#906cff'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'go@{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#7FD5EA'
    type = 'go'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'js@{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#76b367'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'ruby@{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#f44336'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'java@{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ea2d2e'
    type = 'java'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'julia@ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#4063D8'
    type = 'julia'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '$'
    foreground = '#FFFFFF'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
